name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    name: Test and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.6.3

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('tests/playwright/package.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright in tests/playwright directory
        run: cd tests/playwright && pnpm add -D playwright

      - name: Install Playwright browsers
        run: |
          cd tests/playwright
          pnpm exec playwright install --with-deps chromium

      - name: Run type checking
        run: pnpm playground:check

      - name: Run linting
        run: pnpm playground:lint

      - name: Build playground application
        run: pnpm playground:build

      - name: Start playground app for testing
        run: |
          pnpm playground:preview --port 3000 &
          sleep 10
          curl -f http://localhost:3000 || exit 1

      - name: Run Cucumber E2E tests
        run: pnpm test:cucumber
        env:
          CI: true
          BASE_URL: http://localhost:3000

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            report/playwright/
            tests/playwright/test-results/
          retention-days: 30

  security:
    name: Security Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.6.3

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run security audit
        run: pnpm audit --audit-level moderate

      - name: Run additional security checks
        run: |
          # Check for known vulnerabilities in dependencies
          pnpm playground:check

          # Verify no sensitive files are committed
          if [ -f .env ]; then
            echo "Error: .env file should not be committed"
            exit 1
          fi
