name: Dependency Review

on:
  pull_request:
    branches: [main, develop]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          # Fail on moderate or higher severity vulnerabilities
          fail-on-severity: moderate

          # Allow specific licenses (adjust as needed)
          allow-licenses: |
            MIT
            Apache-2.0
            BSD-2-Clause
            BSD-3-Clause
            ISC
            0BSD

          # Deny specific licenses
          deny-licenses: |
            GPL-2.0
            GPL-3.0
            AGPL-1.0
            AGPL-3.0

          # Comment on PR with results
          comment-summary-in-pr: always

          # Retry configuration
          retry-on-snapshot-warnings: true
          retry-on-snapshot-warnings-timeout: 120
