name: Dependency Review

on:
  pull_request:
    branches: [main, develop]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          # Fail on high or critical severity vulnerabilities
          fail-on-severity: high

          # can only specify allow or deny, not both
          # Allow-list example: see project documentation or issue tracker for details if needed

          # Only deny truly problematic licenses
          deny-licenses: GPL-3.0-only, AGPL-3.0

          # Comment on PR with results
          comment-summary-in-pr: always

          # Retry configuration
          retry-on-snapshot-warnings: true
          retry-on-snapshot-warnings-timeout: 120
